import type { Metadata } from "next";
import { AuthProvider } from "./context/AuthContext";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import ChatBox from "./components/chatBox/chatbox";

const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Room Sewa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${plusJakarta.variable} h-full antialiased`}
    >
      <body
        className="min-h-full flex flex-col"
        suppressHydrationWarning
      >
        <AuthProvider>
          {children}
        </AuthProvider>
        <ChatBox/>
      </body>
    </html> 
  );
}